// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpd_Rbi0wzfPuJmRXzRbXBbKdDSN9dZog',
    appId: '1:101704680480:web:950d31c617d4394a816845',
    messagingSenderId: '101704680480',
    projectId: 'taptobeat-cd62f',
    authDomain: 'taptobeat-cd62f.firebaseapp.com',
    storageBucket: 'taptobeat-cd62f.firebasestorage.app',
    measurementId: 'G-JFE1FY4GSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPmbYb1olF7F0eDh5kjsJuj8WzfzYxX3U',
    appId: '1:101704680480:android:b9b95f350f84d48b816845',
    messagingSenderId: '101704680480',
    projectId: 'taptobeat-cd62f',
    storageBucket: 'taptobeat-cd62f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBskzzm35iLY_yrt6s9wsVSdS4n0B1R73o',
    appId: '1:101704680480:ios:490a586d343aec60816845',
    messagingSenderId: '101704680480',
    projectId: 'taptobeat-cd62f',
    storageBucket: 'taptobeat-cd62f.firebasestorage.app',
    iosClientId: '101704680480-rl0ccr3sumbbehjr1ddkqu3r7arr8ses.apps.googleusercontent.com',
    iosBundleId: 'com.han.TapToBeat',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBskzzm35iLY_yrt6s9wsVSdS4n0B1R73o',
    appId: '1:101704680480:ios:490a586d343aec60816845',
    messagingSenderId: '101704680480',
    projectId: 'taptobeat-cd62f',
    storageBucket: 'taptobeat-cd62f.firebasestorage.app',
    iosClientId: '101704680480-rl0ccr3sumbbehjr1ddkqu3r7arr8ses.apps.googleusercontent.com',
    iosBundleId: 'com.han.TapToBeat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpd_Rbi0wzfPuJmRXzRbXBbKdDSN9dZog',
    appId: '1:101704680480:web:fd13d2e61b035993816845',
    messagingSenderId: '101704680480',
    projectId: 'taptobeat-cd62f',
    authDomain: 'taptobeat-cd62f.firebaseapp.com',
    storageBucket: 'taptobeat-cd62f.firebasestorage.app',
    measurementId: 'G-FT7XTJ9S3P',
  );
}
