// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBldRalyQABO_dAOIM8MwmiDbHBbXJ0Ihs',
    appId: '1:185826763880:web:964e3dc62de8ee9e3ec7dd',
    messagingSenderId: '185826763880',
    projectId: 'taptobeat-98b40',
    authDomain: 'taptobeat-98b40.firebaseapp.com',
    storageBucket: 'taptobeat-98b40.firebasestorage.app',
    measurementId: 'G-LHF3LQW9NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArXn5vjAAAW0boeLTixU7U6LM-CpZtv0s',
    appId: '1:185826763880:android:fa5517a05c33d0473ec7dd',
    messagingSenderId: '185826763880',
    projectId: 'taptobeat-98b40',
    storageBucket: 'taptobeat-98b40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUw1Vd42dEVGiCKUApkrabyl1SOXZsUJE',
    appId: '1:185826763880:ios:47847316bbba0ffa3ec7dd',
    messagingSenderId: '185826763880',
    projectId: 'taptobeat-98b40',
    storageBucket: 'taptobeat-98b40.firebasestorage.app',
    iosClientId: '185826763880-c98nhes30600350oqbntt4dijjd758cs.apps.googleusercontent.com',
    iosBundleId: 'com.han.TapToBeat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUw1Vd42dEVGiCKUApkrabyl1SOXZsUJE',
    appId: '1:185826763880:ios:47847316bbba0ffa3ec7dd',
    messagingSenderId: '185826763880',
    projectId: 'taptobeat-98b40',
    storageBucket: 'taptobeat-98b40.firebasestorage.app',
    iosClientId: '185826763880-c98nhes30600350oqbntt4dijjd758cs.apps.googleusercontent.com',
    iosBundleId: 'com.han.TapToBeat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBldRalyQABO_dAOIM8MwmiDbHBbXJ0Ihs',
    appId: '1:185826763880:web:4eb2afb66521f6b23ec7dd',
    messagingSenderId: '185826763880',
    projectId: 'taptobeat-98b40',
    authDomain: 'taptobeat-98b40.firebaseapp.com',
    storageBucket: 'taptobeat-98b40.firebasestorage.app',
    measurementId: 'G-2WYV2RG24Z',
  );
}
